name: Build Flutter APK Auto

on:
  workflow_dispatch:
    inputs:
      job_id:
        description: "ID dari bot (opsional)"
        required: false
        default: ""
      zip_url:
        description: "Link zip project"
        required: true
      zip_path:
        description: "Path zip di repo (opsional)"
        required: false
        default: ""

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Job ID (fallback)
        id: job
        run: |
          if [ -z "${{ inputs.job_id }}" ]; then
            echo "job_id=$(date +%s)" >> $GITHUB_OUTPUT
          else
            echo "job_id=${{ inputs.job_id }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Prepare Project
        run: |
          set -e
          mkdir work
          cd work

          if [ -n "${{ inputs.zip_url }}" ]; then
            echo "Download dari link..."
            curl -L --fail "${{ inputs.zip_url }}" -o project.zip
          elif [ -n "${{ inputs.zip_path }}" ]; then
            echo "Ambil dari repo..."
            cp "../${{ inputs.zip_path }}" project.zip
          else
            echo "ERROR: zip wajib diisi!"
            exit 1
          fi

          unzip project.zip -d project

      - name: Install dependencies
        working-directory: work/project
        run: flutter pub get

      - name: Build APK
        working-directory: work/project
        run: flutter build apk --release

      - name: Rename APK
        run: |
          mkdir out
          cp work/project/build/app/outputs/flutter-apk/app-release.apk out/app-${{ steps.job.outputs.job_id }}.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ steps.job.outputs.job_id }}
          path: out/*.apk
